### DISCUSSION TITLE
RED should also match PTH torrents

### DISCUSSION THREAD

**Discussion by RogueOneEcho** [RogueOneEcho/caesura#112] [Ideas]
Older RED torrents have the source set to `PTH` rather than `RED`.

As the `batch` command explicitly checks the source field of the `.torrent` these are skipped.

As a workaround `PTH` can be treated as a separate indexer similar to how you would have separate configs for `OPS` and `RED`. 

```yaml
indexer_url: https://redacted.sh
indexer: pth
```

**Comment by Asparghus** [comment]
It could also accept a sequence instead of a string. Like target and spectrogram_size.
```
indexer: 
- red
- pth
- ops
indexer_url:
- https://***.sh
- https://***.sh
- https://***.network
```

**Reply by RogueOneEcho** [reply]
As it's an edge case I think it's probably easier just to hard code logic rather than making it configurable.

**Reply by Asparghus** [reply]
I agree when it comes to red and pth. 
But that could still be used to simplify the cross upload between red and ops if used in conjunction with announce_url and api_key
```
announce_url: 
- redAnnounce
- opsAnnounce
api_key:  
- redAPI
- opsAPI
indexer: 
- red
- ops
indexer_url:
- https://***.sh
- https://***.network
```

**Reply by RogueOneEcho** [reply]
IMO that format just looks clunky.

The preference would be to transpose it to:

```
indexers:
  red:
    announce_url: VALUE
    api_key: VALUE
    indexer_url: VALUE
    tracker_url: VALUE
  ops:
    announce_url: VALUE
    api_key: VALUE
    indexer_url: VALUE
    tracker_url: VALUE
```

Which is fine for a config.yml file but it's much harder to map with cli args. This could technically work but I suspect it would need custom parsing rather than relying on the `clap` crate

```bash
casesura batch --indexer red --announce_url VALUE --api_key VALUE --indexer_url VALUE --tracker_url VALUE --indexer ops --announce_url VALUE --api_key VALUE --indexer_url VALUE --tracker_url VALUE
```

It would also be a pretty major change to internal logic as users will expect both the ops and red APIs to be searched together.
