### DISCUSSION TITLE
Docker compose keeps creating the config.yml file as a directory

### DISCUSSION THREAD

**Discussion by rpgdev** [RogueOneEcho/caesura#126] [Support] [answered]
The docker compose setup keeps creating the config.yml as a directory, not a file. It doesn't seem like the compose recognizes the mount in the compose as a config file either since I still need to point to the config file in the compose command as well.

**Comment by RogueOneEcho** [comment, marked as answer]
It's the standard behaviour of Docker to create a directory for a volume if it doesn't exist. 

To mount the `config.yml` as file it must already exist. 

https://github.com/RogueOneEcho/caesura?tab=readme-ov-file#2-create-a-configuration-file

If you're still having trouble can you share the compose command you're using? Are you certain the config file exists?

**Reply by rpgdev** [reply]
My bad, I assumed the docker image would create an initial config file. Once I created the file myself it worked.

**Comment by b-** [comment]
For this sort of thing, I like using the `configs:` top level element to put my config file inline in the compose file, as follows:

```yaml
configs:
  config.yml:
    content: |
      announce_url: "${announce_url}"
      api_key: "${api_key}"
      content:
        - /var/srv/media/downloads
        - /var/srv/media/downloads/lidarr
      output: /var/srv/apps/caesura/output
      verbosity: debug

services:
  caesura:
    configs:
      - config.yml
    container_name: caesura
    image: ghcr.io/rogueoneecho/caesura
    volumes:
    - /var/srv:/var/srv
    - /var/srv/apps/caesura/cache:/cache
```

You can also drop your announce URL and api key into a .env file to interpret them from variables like above if that's helpful to you, too.
